apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argo-test-manifest
  name: argo-test-manifest-configmap
data:
  index.html: |
    <html>
    <body>
    <h1>Hi, world!</h1>
    </body>
    </html>
