apiVersion: v1
kind: Service
metadata:
  name: argo-test-manifest-nginx-service
  namespace: argo-test-manifest
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
